# Generated by Django 4.2.16 on 2024-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Request", "Request"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                ],
                default="Request",
                max_length=20,
            ),
        ),
    ]
