# Generated by Django 4.2.16 on 2024-10-19 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buddy_requests", "0002_alter_buddyrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buddy",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="buddy",
            name="user2",
        ),
        migrations.AddField(
            model_name="buddy",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buddies_as_recipient",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buddy",
            name="requester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buddies_as_requester",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
