# Generated by Django 4.2.16 on 2024-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy_requests", "0003_remove_buddy_user1_remove_buddy_user2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Request", "Request"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                ],
                default="Request",
                max_length=20,
            ),
        ),
    ]
