# Generated by Django 4.2.16 on 2024-10-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="user_pic",
                to="wagtailimages.image",
            ),
        ),
    ]
