# Generated by Django 4.2.16 on 2024-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_phone_number_customuser_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
