# Generated by Django 4.2.16 on 2024-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_shoppinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
