# Generated by Django 4.2.16 on 2024-12-20 00:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_shoppinglist_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
