# Generated by Django 4.2.16 on 2025-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_store_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="deals",
            field=models.ManyToManyField(blank=True, null=True, to="stores.deal"),
        ),
    ]
