# Generated by Django 4.2.16 on 2025-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_alter_shoppinglist_deals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="deals",
            field=models.ManyToManyField(blank=True, to="stores.deal"),
        ),
    ]
