# Generated by Django 4.2.16 on 2025-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_shoppinglist_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
